# 백엔드 어플리케이션 설정
image:
  repository: 183631327456.dkr.ecr.ap-northeast-2.amazonaws.com/tier3-backend
  tag: backend-v1.0_20250327015123
  pullPolicy: Always

replicaCount: 1

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # External DNS 어노테이션
    external-dns.alpha.kubernetes.io/hostname: api.mydairy.my
  hosts:
    - host: api.mydairy.my
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

environment: dev

# 데이터베이스 연결 설정 추가
database:
  host: "localhost"  # 기본값, 실제로는 ArgoCD에서 오버라이드됨
  port: 3306        # 기본값, MySQL/MariaDB 기본 포트
  name: "mydairy"   # 기본값
  username: "admin"  # 기본값
  password: ""      # 기본값, 실제로는 ArgoCD에서 오버라이드됨
  
  # DB 연결 설정
  connectionPoolSize: 10
  maxLifetime: 1800
  maxIdleTime: 600
