apiVersion: v1
kind: Secret
metadata:
  name: frontend-db-credentials
  labels:
    app: frontend
type: Opaque
data:
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }} 