name: 백엔드 이미지 빌드 및 ECR 배포
on:
  push:
    branches: [master]
    paths:
      - 'src/**' # 백엔드 코드가 변경될 때만 실행
env:
  AWS_REGION: ap-northeast-2 # AWS 리전을 서울로 지정
  ECR_REPOSITORY: tier3-backend # ECR 리포지토리 이름
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: 현재 시간 가져오기
        id: current-time
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
      - name: Jib로 이미지 빌드 및 ECR 푸시
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: petclinic-backend
          IMAGE_TAG: ${{ github.sha }}
          TIMESTAMP_TAG: ${{ steps.current-time.outputs.timestamp }}
        run: |
          # pom.xml에 명시된 이미지 레지스트리와 태그를 오버라이드
          mvn compile jib:build \
            -Djib.to.image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -Djib.to.tags=latest,$TIMESTAMP_TAG
          
          # 출력 설정
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
      # ArgoCD 매니페스트 업데이트
      - name: Git 설정
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions@github.com"
      - name: ArgoCD 매니페스트 업데이트
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: petclinic-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # values.yaml 파일 업데이트 (이미지 태그만)
          sed -i "s|tag:.*|tag: $IMAGE_TAG|g" argocd/charts/backend/values.yaml
          sed -i "s|repository:.*|repository: $ECR_REGISTRY/$ECR_REPOSITORY|g" argocd/charts/backend/values.yaml
          
          # 변경사항 커밋 및 푸시
          git add argocd/charts/backend/values.yaml
          git commit -m "백엔드 이미지 업데이트: $IMAGE_TAG"
          git push
